config/routes.rb
Rails.application.routes.draw do
  get 'reviews/index'
  get 'reviews/new'
  get 'reviews/create'
  get 'restaurants/index'
  get 'restaurants/show'
  get 'restaurants/new'
  get 'restaurants/create'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :restaurants, only: [:index, :show, :new, :create] do
    resources :reviews, only: [:create]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  has_many :reviews, dependent: :destroy
  validates :name, presence: true
  validates :address, presence: true
  validates :category, presence: true, inclusion: { in: ["chinese", "italian", "japanese", "french", "belgian"],
    message: "%{value} is not a valid category" }
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :restaurant
  validates :rating, presence: true, numericality: { only_integer: true, greater_than_or_equal_to: 0, less_than_or_equal_to: 5 }
  validates :content, presence: true
  validates_associated :restaurant
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  before_action :set_restaurant, only: [:show]

  def index
    @restaurants = Restaurant.all
  end

  def show
    @review = Review.new
  end

  def new
    @restaurant = Restaurant.new
  end

  def create
    @restaurant = Restaurant.create(restaurant_params)
    @restaurant.save

    if @restaurant.save
      redirect_to restaurant_path(@restaurant)
    else
      render :new
    end
  end

  private

  def set_restaurant
    @restaurant = Restaurant.find(params[:id])
  end

  def restaurant_params
    params.require(:restaurant).permit(:name, :address, :phone_number, :category)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def index
    @restaurant = Restaurant.find(params[:restaurant_id])
    @reviews = @restaurant.reviews
  end

  def new
    @restaurant = Restaurant.find(params[:restaurant_id])
    @review = Review.new
  end

  def create
    @review = Review.new(review_params)
    @restaurant = Restaurant.find(params[:restaurant_id])
    @review.restaurant = @restaurant

    if @review.save
      redirect_to @review.restaurant
    else
      render "restaurants/show"
    end
  end

  private

  def review_params
    params.require(:review).permit(:rating, :content)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsYelpMvp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="jumbotron jumbotron-fluid">
      <div class="container">
        <h1 class="display-4"><%= link_to "The world best restaurant reviews", restaurants_path %></h1>
      </div>
    </div>
    <%= yield %>
  </body>
</html>

app/views/restaurants/_new_review.html.erb
<div class="container">
  <h1>Add a new restaurant review</h1>
  <%= simple_form_for [@restaurant, @review] do |f| %>
    <%= f.input :rating %>
    <%= f.input :content %>
    <%= f.button :submit, class: "btn btn-primary" %>
  <% end %>
</div>

app/views/restaurants/_restaurant.html.erb
<div class="card col-6">
  <h1><%= link_to "#{restaurant.name}", restaurant_path(restaurant) %></h1>
    <div>
      <p><i>Category: <%= restaurant.category %></i></p>
    </div>
    <div>
      <p><strong>Address:</strong> <%= restaurant.address %></p>
      <p><strong>Phone Number:</strong> <%= restaurant.phone_number %></p>
    </div>
</div>

app/views/restaurants/create.html.erb
<h1>Restaurants#create</h1>
<p>Find me in app/views/restaurants/create.html.erb</p>

app/views/restaurants/index.html.erb
<div class="container">
  <%= link_to "Create new restaurant listing", new_restaurant_path, class: "btn btn-primary" %>
  <h1>Find your favourite restaurant!</h1>
  <div class="row">
    <%= render @restaurants %>
  </div>
</div>

app/views/restaurants/new.html.erb
<div class="container">
  <h1>Create a new restaurant listing</h1>
  <%= simple_form_for(@restaurant) do |f| %>
    <%= f.input :name %>
    <%= f.input :address %>
    <%= f.input :phone_number %>
    <%= f.input :category, collection: ["chinese", "italian", "japanese", "french", "belgian"] %>
    <%= f.button :submit, class: "btn btn-primary" %>
  <% end %>
  <%= link_to "Return to view all restaurants", restaurants_path %>
</div>

app/views/restaurants/show.html.erb
<div class="container">
  <%= render @restaurant %>
</div>
<div class="container">
  <%= link_to "Return to view all restaurants", restaurants_path, class: "btn btn-primary" %>
</div>
<%= render @restaurant.reviews %>
<%= render "restaurants/new_review", restaurant: @restaurant, review: @review %>

app/views/reviews/_review.html.erb
<div class="container">
  <li class="list-group-item">
    <p><strong>Rating: <%= review.rating %></strong></p>
    <p><strong><u>Comment:</u></strong></p>
    <p><%= review.content %></p>
  </li>
</div>

app/views/reviews/create.html.erb
<h1>Reviews#create</h1>
<p>Find me in app/views/reviews/create.html.erb</p>

app/views/reviews/index.html.erb
<%= render @reviews %>

app/views/reviews/new.html.erb
<h1>Reviews#new</h1>
<p>Find me in app/views/reviews/new.html.erb</p>